server:
    error:
        include-stacktrace: ON_PARAM

spring:
    datasource:
        url: jdbc:mysql://31.170.160.154:3306/u752060425_publisocial?useSSL=false&createDataBaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: u752060425_publiuser
        password: Projeto13
    jpa:
        hibernate:
            ddl-auto: update